sonar.projectKey=copy-clipboard-all
sonar.projectName=copy-clipboard-all
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,coverage.out

sonar.go.coverage.reportPaths=coverage.out
